### ISSUE TITLE
RSS Feature

### ISSUE THREAD

**Issue by keypulse** [JohnVanOrange/FrontEnd#104]
By adding the ability to RSS feed the random links, one can use JVO for their xscreensaver seed (if they dare).  The feature could be sorted by making use of the tag cloud as well, for NSFW avoidance.

**Comment by cbulock** [comment]
Commit fb975eca93f721e122400ffbb01d67a91070d2ee

This should be done.  The RSS feed can be found at http://jvo.io/rss

Haven't actually tested this with xscreensaver.  Let me know if anything needs to be updated to make it work
